name: chat_gpt_clone
description: A ChatGPT clone built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.4.9
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  uuid: ^4.2.1
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  dio: ^5.3.3
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700 